version: '3.8'

services:
  osrm:
    image: osrm/osrm-backend:latest
    container_name: osrm
    volumes:
      - ./data:/data
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "5000:5000"
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
