package com.mssus.app.common.enums;

public enum NotificationType {
    RIDE_REQUEST,
    RIDE_CONFIRMED,
    RIDE_STARTED,
    RIDE_COMPLETED,
    PAYMENT,
    PROMOTION,
    SYSTEM,
    EMERGENCY,
    RIDE_TRACKING_START,
    WALLET_HOLD,
    WALLET_CAPTURE,
    WALLET_RELEASE,
    WALLET_REFUND,
    WALLET_PAYOUT,
    BOOKING_REQUEST_CREATED,
    JOIN_RIDE_REQUEST_CREATED,
    RIDE_AUTO_STARTED,
    RIDE_AUTO_COMPLETED,
    REQUEST_AUTO_STARTED,
    REQUEST_AUTO_COMPLETED,
    REQUEST_STARTED,
    REQUEST_COMPLETED
}
